[project]
name = 'Demo-Gods-Pacifier'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.latency-illusionist]
path = 'contracts/latency-illusionist.clar'
clarity_version = 3
epoch = 'latest'

[contracts.offline-mock-swapper]
path = 'contracts/offline-mock-swapper.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
